### ISSUE TITLE
ingress not working

### ISSUE THREAD

**Issue by DrissiReda** [bentoml/yatai-chart#3]
I'm unable to query the service through the ingress:

what I'm trying and getting

```sh
$ grpcurl -plaintext yatai.locahost:80 hi/there
Failed to dial target host "yatai.localhost:80": context deadline exceeded
$ grpcurl -plaintext yatai.locahost:443 hi/there
Failed to dial target host "yatai.localhost:443": context deadline exceeded
```

If I use a `kubectl port-forward` it works better:

```sh
$ grpcurl -plaintext localhost:50051 hi/there
Error invoking method "hi/there": failed to query for service descriptor "hi": server does not support the reflection API
```

So I'm suspecting that the problem is with the ingress, I'm using everything in default from `master`.

My k8s cluster has other services, so I know the ingress itself works (e.g s3, yatai-ui, etc)

**Comment by yubozhao** [comment]
@DrissiReda We release brand new Yatai service. Let me know if you got a chance to try it out. 
Going to close this issue for now, feel free to reopen it.
