### ISSUE TITLE
Support a Non-NodePort Service

### ISSUE THREAD

**Issue by KnechtionsCoding** [bentoml/yatai-chart#37]
Allow configuration of the service, specifically type to not be node port if there is alternatives in the cluster

**Comment by yetone** [comment]
@KnechtionsCoding Thank you for your feedback, the configuration item is already available here

https://github.com/bentoml/yatai-chart/blob/c4b45b2d3d7b6a914842df2f327eb5875c42a15d/values.yaml#L61
