### ISSUE TITLE
reinstall yatai with helm ,the pods is CrashLoopBackOff;use delete script make the namespaces Terminating

### ISSUE THREAD

**Issue by zhuyaguang** [bentoml/yatai-chart#52]
the pods is CrashLoopBackOff
![image](https://user-images.githubusercontent.com/8857976/181219251-89b56e03-a953-4cfd-ae60-5d9e221ae2a4.png)

the  delete script is hang 

![image](https://user-images.githubusercontent.com/8857976/181219526-c2247cab-f92e-4c71-99ae-8121c3525c9d.png)

and the namespaces is Terminating can not delete 

![image](https://user-images.githubusercontent.com/8857976/181219714-93430cd2-84bd-4911-a70f-cc54184bff40.png)

**Comment by yetone** [comment]
You can run the following command to delete the namespace:

```bash
NAMESPACE=yatai-components; kubectl proxy &; kubectl get namespace $NAMESPACE -o json | jq '.spec = {"finalizers":[]}' > temp.json; curl -k -H "Content-Type: application/json" -X PUT --data-binary @temp.json 127.0.0.1:8001/api/v1/namespaces/$NAMESPACE/finalize

NAMESPACE=yatai-system; kubectl proxy &; kubectl get namespace $NAMESPACE -o json | jq '.spec = {"finalizers":[]}' > temp.json; curl -k -H "Content-Type: application/json" -X PUT --data-binary @temp.json 127.0.0.1:8001/api/v1/namespaces/$NAMESPACE/finalize
```

**Comment by yetone** [comment]
Sounds great, thanks for the feedback, I will close this issue in light of the resolution
